version: '3.4'

services:
  jenkins:
    build: .
    restart: unless-stopped
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "${JENKINS_PORT}:8080"
    secrets:
      - jenkins-username
      - jenkins-password
      - github-username
      - github-access-token
    environment:
      - JENKINS_URL
      - GO_VERSION
      - GOLANGCI_LINT_VERSION

volumes:
  jenkins_home:

secrets:
  jenkins-username:
    file: /tmp/jenkins-secrets-jenkins-username
  jenkins-password:
    file: /tmp/jenkins-secrets-jenkins-password
  github-username:
    file: /tmp/jenkins-secrets-github-username
  github-access-token:
    file: /tmp/jenkins-secrets-github-access-token
