#!/usr/bin/env bash

golangci-lint-install

cfg=$(find . -regex '\./.golangci.\(yml\|toml\|json\)' | head -n 1)
cfgsrc="${cfg}"

if [[ -z "${cfg}" ]]; then
    cfg="${GOLANGCI_LINT_PATH}/.golangci.yml"
    cfgsrc="default"
fi

go get

echo
echo Running with config file: ${cfgsrc}
echo

golangci-lint run -c ${cfg}
